apiVersion: v1
kind: Service
metadata:
  name: guestbook_v2-service
  labels:
    app: guestbook_v2-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook_v2-pod